### ISSUE TITLE
Fast plots for FV3 fields

### ISSUE THREAD

**Issue by benjaminmenetrier** [danholdaway/fv3jedi_static_b_tools#22]
## Description

I'm running experiments with FV3-JEDI at C384 on Orion, but plotting fields with Python using the `src/raster/raster.py` is veeeery slow (more that 4 min for a single variable at a given level).

My question is: would you have scripts to plot FV3 fields faster?
- I checked that loading data is fast, but plotting them is the slow part.
- Python would be great, but I'm open to any other language.
- I can't download data on my own workstation (too slow), I can download figures only.
- I'm using the following environment for Python:
```
export JEDI_OPT=/work/noaa/da/jedipara/opt/modules
module purge
module use $JEDI_OPT/modulefiles/core
module load jedi/gnu-openmpi
module load geos proj
```

Any help would be much appreciated.

**Comment by weihuang-jedi** [comment]
@benjaminmenetrier Could you please point me your data on orion, and what you want to plot then I'd like to take a look.
I have some Python plotting scripts, I'd like to try if that can serve your purpose.

**Comment by cmgas** [comment]
You can plot latlon files with the fv3-jedi-tools module, have you tried this?
EDIT: didn't see the repo for this issue, I'm sorry

**Comment by benjaminmenetrier** [comment]
@weihuang-jedi: I would like to plot data written by FV3-JEDI, either in "gfs" or in "geos" format. For instance, I have data in "gfs" format here: /work/noaa/da/menetrie/StaticBTraining/c384/bump_gsi/dirac_cor_local

**Comment by weihuang-jedi** [comment]
@benjaminmenetrier could you please open the permission?

(base) bash-4.2$ cd /work/noaa/da/menetrie/StaticBTraining/c384/bump_gsi/dirac_cor_local
bash: cd: /work/noaa/da/menetrie/StaticBTraining/c384/bump_gsi/dirac_cor_local: Permission denied

**Comment by benjaminmenetrier** [comment]
Sorry! Access rights should be fine now, let me know if it is not the case.

**Comment by weihuang-jedi** [comment]
I have a simple python script on orion: ~weihuang/exm.py

Please take a look to see if this can serve your purpose.
I use 't' here. You may try other variables.

**Comment by benjaminmenetrier** [comment]
Denise Worthen from NOAA suggested to use **ferret**, which was a very good idea. Thank you @climbfuji for contacting her.
A PR including ferret as an option of `raster.py` is available here: https://github.com/JCSDA-internal/fv3-jedi-tools/pull/23
