### ISSUE TITLE
Update code to build static B matrix for CO and NO2

### ISSUE THREAD

**Issue by jeromebarre** [danholdaway/fv3jedi_static_b_tools#30]
## Description

The code sprint on the B matrix will come too late so we would still need to update the code for the B matrix training on this repo for CO and NO2.
Use branch https://github.com/JCSDA-internal/fv3-jedi-tools/tree/feature/test-aero-for-s4 (update and fix conflict from last update on develop).
Get ensemble data from @christophkeller with preliminary perturbation and then final (we need to look at which ensemble spread make more sense between the different perturbation flavors).

Then compute the final static B for the golden month of Aug 2021.

## Requirements

Get ensemble data from @christophkeller 

## Acceptance Criteria (Definition of Done)

The static B matrix runs with skylab-tracegas experiment and produce resonable converge and increments.

## Dependencies

Get ensemble data from @christophkeller

**Comment by jeromebarre** [comment]
@mer-a-o is this finished?

**Comment by mer-a-o** [comment]
@jeromebarre The code has been updated (`feature/staticb-geos-cf-discover` of `fv3-jedi-tools`) but we still need to tune it further for more reasonable results. We can either close this one and open a more specific one or just keep this open.

**Comment by jeromebarre** [comment]
Closing this now, the code is there. It is now a matter of having better ensemble to train with.
